ALTER TYPE "public"."permission_action" ADD VALUE 'categories:read:global';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'categories:create:global';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'categories:update:global';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'categories:delete:global';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'categories:read:tenant';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'categories:create:tenant';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'categories:update:tenant';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'categories:delete:tenant';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'products:read:global';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'products:create:global';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'products:update:global';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'products:delete:global';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'products:read:tenant';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'products:create:tenant';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'products:update:tenant';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'products:delete:tenant';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'warehouses:read:global';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'warehouses:create:global';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'warehouses:update:global';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'warehouses:delete:global';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'warehouses:read:tenant';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'warehouses:create:tenant';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'warehouses:update:tenant';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'warehouses:delete:tenant';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'suppliers:read:global';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'suppliers:create:global';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'suppliers:update:global';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'suppliers:delete:global';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'suppliers:read:tenant';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'suppliers:create:tenant';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'suppliers:update:tenant';--> statement-breakpoint
ALTER TYPE "public"."permission_action" ADD VALUE 'suppliers:delete:tenant';