export enum HTTP_STATUS_CODE {
  OK = 200,
  CREATED = 201,
  NO_CONTENT = 204,
  INTERNAL_SERVER_ERROR = 500,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  BAD_REQUEST = 400,
  CONFLICT = 409,
}

export enum HTTP_STATUS_CODE_TEXT {
  SUCCESS = "success",
  FAIL = "fail",
  ERROR = "error",
}
